version: '3'
services: 
    oracle:
      container_name: oracledb2
      image: gvenzl/oracle-xe
      environment:
        - ORACLE_PASSWORD= aaa
      ports:
        - 1522:1521
        - 5500:5500
      volumes:
        - "./data:/opt/oracle/oradata"
      